format_version: 10
environments:
  oscap:
    pipelines:
    - oscap
    agents:
    - 0703d527-7667-4e89-9bc9-31d3501c03a2
    - 781900c5-909e-4410-8333-9467ab2d1a53
pipelines:
  oscap:
    group: oscap
    environment: OpenSCAP
    materials:
      oscap-maint-1.3:
        github: git@github.com:OpenSCAP/openscap.git
        shallow_clone: true
        branch: maint-1.3-gocd
    stages:
    - build-and-test:
        fetch_materials: true
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          build-and-test:
            tasks:
            - exec:
                arguments:
                - ..
                command: cmake
                working_directory: build
            - exec:
                command: make
                working_directory: build
            - exec:
                arguments:
                - --output-on-failure
                - -R
                - yaml
                command: ctest
                working_directory: build
